### ISSUE TITLE
Return of the web based GO slim tool

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#283] opened 2015-11-18 08:19 UTC
Will the web based GO slim tool be returning at any point?
see comments in this ticket 
http://jira.geneontology.org/browse/GO-1027

PomBase currently  point users to 
http://go.princeton.edu/cgi-bin/GOTermMapper
rather than QuickGO because it matches our output
http://www.pombase.org/browse-curation/fission-yeast-go-slim-terms

We don't want to point  our users to QuickGO because  the GO annotations are differently in GOA than in GO 
1. We have filtered all of the annotations generated by erroneous mappings submitted to this tracker
https://github.com/geneontology/go-annotation/issues
AND  
2. GOA/QuickGO filter annotations for syntax errors which are currently accepted by the 
GO loading script.
https://github.com/geneontology/go-site/issues/123

**Comment by kltm** [comment] 2015-11-18 08:25
You might want to try searching for keywords before adding items. This seems to be a dupe of #144 .

**Closed by kltm** 2015-11-18 08:25 UTC
