### ISSUE TITLE
table rendering issues in amigo labs

### ISSUE THREAD

**Issue by jmcmurry** [geneontology/amigo#442] opened 2017-09-26 05:51 UTC
Table contents overshoot table boundaries [here](http://amigo2.berkeleybop.org/amigo/gene_product/ZFIN:ZDB-GENE-091204-466).

<img width="416" alt="screen shot 2017-09-25 at 10 49 15 pm" src="https://user-images.githubusercontent.com/3658863/30844454-f3076c6a-a243-11e7-9bb7-061523b04717.png">

**Comment by kltm** [comment] 2017-09-26 06:08
Dupe of #398 .

**Closed by kltm** 2017-09-26 06:08 UTC
Labels: duplicate

**Comment by kltm** [comment] 2017-09-26 06:15
If you look at the other issue, *technically* I believe the widget renders the table fine, but BS3 is unable to productively handle the overflow. Not that that bit of plumbing knowledge helps the users...
