### ISSUE TITLE
Human gene products inflated

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#477] opened 2018-03-08 09:10 UTC
17510 from UniProt (which seems to be all annotated human gene products)
8591 as HGNC (PANther annotation), which are exact duplicates form PAnther

so for example MRPL39
http://amigo2.berkeleybop.org/amigo/search/bioentity?q=MRPL39

Please, please can this be fixed. We can't use human annotation for any analysis whilst this issue persists.

**Comment by cmungall** [comment] 2018-03-08 18:15
See my comment here https://github.com/geneontology/helpdesk/issues/99#issuecomment-371574707 for an explanation of why this is persists

**Comment by kltm** [comment] 2018-03-12 20:45
Dupe of: https://github.com/geneontology/helpdesk/issues/99

**Closed by kltm** 2018-03-12 20:45 UTC
Labels: bug (A: showstopper), duplicate
