### ISSUE TITLE
Filter annotations by evidence is not working

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/amigo#716] opened 2024-04-09 13:36 UTC
When viewing a list of annotations in AmiGO, it is no longer possible to filter by Evidence.

Clicking on the Evidence facet says 'Nothing to filter'.

![image](https://github.com/geneontology/amigo/assets/1730534/93e68306-8c2d-43b7-b8c6-be5eafb564e3)

This may also be related to an issue with the Noctua Search Annotations functionality reported today by @pmasson55

https://github.com/geneontology/noctua-visual-pathway-editor/issues/75

**Comment by kltm** [comment] 2024-04-09 15:17
After the last GO release, evidence filters are no longer working in AmiGO.

To reproduce:

- Go to: https://amigo.geneontology.org/amigo/search/annotation
- Open Evidence filter
- it is empty

The evidence filter should contain a fair number of entries.

**Comment by kltm** [comment] 2024-04-09 15:30
Seems specific to "Evidence" only. Hm.

**Comment by kltm** [comment] 2024-04-09 16:23
Noting that the loaded ontology would have been `ontology/extensions/go-amigo.owl`

There have been no changes to the loading software since the last release, so I think it's safe to put that to the side.

The likely fruitful paths are:
- there was something that happened in the pipeline changes (which seems unlikely as everything seems to have been fine _except_ evidence_
- there was a change in ECO that had some effect
- there was a change in the ontology build or build of go-amigo.owl that had some effect

I'm still digging around on the first on that list, but so far nothing.
We likely need to slide into damage control for the moment: leave as-is or revert to last AmiGO index (and add warning note).

**Comment by kltm** [comment] 2024-04-09 17:03
@balhoff Yes, could be, but it looks like we have not dug down very far in that ticket.
Talking to @pgaudet , she is leery about jumping back to the previous (~2m/o) index to "fix" things as a temporary measure. If we want to go with the ECO-not-getting-through theory, we would either need to dig in there or go back to loading files separately (at least in the short term).

**Comment by kltm** [comment] 2024-04-09 17:47
With @balhoff 's PR in, I'd proposed we start a rebuild and check on staging.

**Comment by kltm** [comment] 2024-04-09 22:41
`snapshot` attempt underway. If things go well, we could maybe have product to look at later tomorrow.

**Comment by kltm** [comment] 2024-04-09 23:55
Noting report from @raymond91125 about the knock-on effects to go-annotation reports.

**Comment by kltm** [comment] 2024-04-10 23:31
We have tested @balhoff 's fix, which seems good for the "Evidence" filter, but are waiting on shifting to a release due to other issues.

**Comment by suzialeksander** [comment] 2024-04-17 23:54
@kltm (or @dustine32 might know) do we have an ETA for a fix? Does this need to wait for next week's outage or is there a chance it will be fixed before that?

**Comment by kltm** [comment] 2024-04-18 03:58
@suzialeksander This independent on any outage--it is tied to a new release.
We have discussed how to proceed with some "problematic sources" that occurred since last release (see https://github.com/geneontology/pipeline/issues/373) and have just started a run that could potentially fix everything. The soonest possible deployment would be Friday or into the weekend, but that would depend on other sources, etc., being as we expect.

**Comment by kltm** [comment] 2024-04-20 04:18
Now in production.

**Comment by kltm** [comment] 2024-04-20 04:19
@vanaukenk When you have time, can you check the expression of this in Noctua?

**Closed by kltm** 2024-04-20 04:18 UTC
Labels: bug (B: affects usability)

**Comment by pgaudet** [comment] 2024-04-22 15:51
Noctua's "Search annotation" functionality works for me.

**Comment by vanaukenk** [comment] 2024-04-23 14:40
Yes, this looks to be working again in Noctua.

Thanks @balhoff @kltm
