### ISSUE TITLE
Default view to mask out redundant automatic annotations

### ISSUE THREAD

**Issue by selewis** [geneontology/amigo#347] opened 2016-04-20 15:15 UTC
"Strip out redundant TAS/ISS/IEA etc annotations that are covered by experimental annotations"
From the Geneva meeting, minutes are sketchy, but here's the link: 

https://docs.google.com/document/d/12CDf4s8YsylPMNHM3UuPis9NyVQ9WFpBpNYTFYAH7kc/edit#heading=h.t9fwrmp9dd6o 

Basically reduce the noise level. These computed annotations offer no additional information about the gene product.

**Comment by kltm** [comment] 2016-04-20 20:50
I believe this is a dupe of #43, or should at least be merged over.

**Comment by kltm** [comment] 2016-04-20 20:50
And/or #294.

**Closed by kltm** 2016-04-20 20:50 UTC
Labels: enhancement
