### ISSUE TITLE
UniProt ID in search string does not locate entry

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#514] opened 2018-07-06 03:45 UTC
From
https://github.com/geneontology/go-annotation/issues/2018

http://amigo.geneontology.org/amigo/medial_search?q=U3KPV4

Nothing found for U3KPV4. Please try again.

http://amigo.geneontology.org/amigo/gene_product/UniProtKB:U3KPV4

works?

**Comment by ValWood** [comment] 2018-07-06 03:57
I  know that I see options if I add a space, but it would not occur  to me that I needed to add a space after an ID and that I could not just hit enter

![no dropdown](https://user-images.githubusercontent.com/7359272/42359307-fdfabedc-80d8-11e8-9b10-9ca9fdfa5427.jpg)

**Comment by ValWood** [comment] 2018-07-06 03:59
OK the pop up does appear without the space. I don't usually wait that long though, and I should still find the correct entry with the ID....

**Comment by kltm** [comment] 2018-07-06 19:09
Duplicate of https://github.com/geneontology/amigo/issues/120

**Closed by kltm** 2018-07-06 19:09 UTC
