### ISSUE TITLE
Add link to FAQ from AmiGO page

### ISSUE THREAD

**Issue by mcourtot** [geneontology/amigo#223] opened 2015-08-12 09:32 UTC
The GO helpdesk is receiving frequent requests linked to size of queries being too large for the enrichment analysis tool. The "Help" link sends to the AmiGO landing page on the GO wiki - could we redirect this towards http://geneontology.org/faq-page (perhaps with an HTML anchor to the specific amigo subsection)?

**Comment by kltm** [comment] 2015-08-12 17:53
This is mostly a dupe of #198.

**Comment by kltm** [comment] 2015-08-12 17:54
Feel free to pick up the conversation there.

**Closed by kltm** 2015-08-12 17:53 UTC
Labels: duplicate

**Comment by mcourtot** [comment] 2015-08-12 18:21
I'm not sure it is a duplicate: we are aware of the existing problem and of issue #198 indeed, but in this case we are not asking for resolution of the technical side. Instead when users are on http://amigo.geneontology.org and encounters the issue, clicking on "help" in the menu doesn't lead them anywhere near the FAQ, which means they submit go-helpdesk tickets (which link is present at the bottom of the page). I'm hoping that having the help manu link towards the FAQ would allow at least some of them to understand the issue without emailing the helpdesk. 
I'm adding a link to this from the other ticket as requested.

**Comment by kltm** [comment] 2015-08-12 18:24
Since the "help" button is for the whole page, and AmiGO in general, I don't think the FAQ is the right place to GO. However, since it dumps you out on the wiki page, it would be easy enough to add additional information there in case of trouble.

**Comment by mcourtot** [comment] 2015-08-12 18:36
Thanks that would work too. I'm just a bit confused between the websites/FAQ: should we *move* the amigo related items or just *copy* them? Copy would be safer but then there is the issue of duplicate information getting out of date in one place perhaps. What do you think?

**Comment by kltm** [comment] 2015-08-12 19:18
I think pretty much anything but copying would be good (we've been down that path before and it's too easy for information to become scattered, out of sync, and incorrect).
My preference would be to just link to the relevant items in the FAQ from the AmiGO Help/wiki with and explanation. E.g., if you are having TE problems, look here or the GO Helpdesk, etc.
At some point we may migrate the AmiGO help from the wiki, but there really isn't the bandwidth to do that right now.

**Comment by cmungall** [comment] 2015-08-12 19:47
I would not be sad if the amigo help on the wiki largely went away. First of all the landing page is user-hostile, it's not clear what the user is meant to do with that snippet of information or how to progress from there (except for GOC users who understand how we are meant to be using categories).

The pages aimed at developers are mostly good and probably belong on a wiki long term (but I think they should move to the amigo github wiki).

However, the pages aimed at the average users are less helpful. They are too terse, they don't really explain the individual components well, and you need a deep understanding of amigo terminology to connect the actual application to the relevant parts of the wiki.

For pages like this: http://wiki.geneontology.org/index.php/AmiGO_2_Manual:_Gene_Product_Page

The correct place to do this is clearly inline, tooltips etc. 

Unfortunately Seth has no time to work on this and in any case the docs should be written in collaboration with the biologists. [this part](http://wiki.geneontology.org/index.php/AmiGO_2_Manual:_Term_Page#Term_Information) should be written by someone from the ontology group. Perhaps @mcourtot and I could work on doing some of this (Melanie just did the exact same thing for the new obofoundry pages as it happens).

In the interim, I think linking to the FAQ directly from AmiGO at the top and possibly in other places too is a really good idea. I support adding more info to the FAQ, even if there is the risk of some redundancy with the amigo wiki.
