### ISSUE TITLE
Requesting production refresh to update db-xrefs.yaml-derived metadata

### ISSUE THREAD

**Issue by rbalakri** [geneontology/amigo#245] opened 2015-09-06 22:01 UTC
Hi,
There was a typo in the yaml file which led to a broken URL (see Seth's message below). I have now fixed the 'yaml' file. What Should i do next?

Thanks,

Rama

=====================================================================
This is actually a issue in the upstream data file db-xrefs.yaml at geneontology/go-site. Looking through the history, on March 13, it looks like you changed "example_id" to "example_is", creating a problem with the forwarding:

geneontology/go-site@772f58f

You should fix that and then request that production updates/refreshes amigo. If you're unsure how to do this, create a new ticket on the go-site tracker with your message and this one.

Cheers,

-Seth

**Comment by kltm** [comment] 2015-09-08 17:26
@stuartmiyasato As far as @rbalakri 's request goes, it is independent of data and can (IIRC) be done with a "make install" on the frontends, which should grab the latest version of the file if available.

**Comment by kltm** [comment] 2015-09-08 17:27
Feel free to close refreshing, or you can ping me and I can take care of it.

**Comment by stuartmiyasato** [comment] 2015-09-08 19:40
I ran "make install" on both production AmiGO servers.  I can't confirm whether the expected behavior changes are in place or not.  Can someone test the servers to make sure we're seeing the desired changes?  @kltm , I don't want to close this issue until someone else has looked at the behavior.  Thanks.

**Comment by kltm** [comment] 2015-09-08 19:49
Thank you @stuartmiyasato.
It looks like links work as expect now from #243.
http://amigo.geneontology.org/amigo/gene_product/SGD:S000003723

**Closed by kltm** 2015-09-08 19:49 UTC
Labels: bug (B: affects usability)

**Comment by rbalakri** [comment] 2015-09-08 21:46
Thank you Seth, Stuart. It works.

Rama
