### ISSUE TITLE
MGI ids are non-standard CURIE's, eg. MGI:MGI:1890761

### ISSUE THREAD

**Issue by nathandunn** [geneontology/amigo#494] opened 2018-04-30 21:52 UTC
expected:

- this link should be fine: http://amigo.geneontology.org/amigo/gene_product/MGI:1890761

actual: 
- received a 404 with the above link
- this was the "correct" link: http://amigo.geneontology.org/amigo/gene_product/MGI:MGI:1890761

I tested additional organisms, and didn't see it with anything else.

**Comment by nathandunn** [comment] 2018-04-30 21:53
Also, this is consistent within the GO (MGI:MGI).   If I need to change the way I do link-ins, that is fine, but this seems like it is just incorrect upstream.

**Comment by kltm** [comment] 2018-04-30 22:02
Duplicate of
https://github.com/geneontology/go-site/issues/91

**Closed by kltm** 2018-04-30 22:02 UTC
