### ISSUE TITLE
regulates closure for Molecular Function in AmiGO

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#417] opened 2017-01-10 14:50 UTC
I notice that if you query on adenylate cyclase:
http://amigo.geneontology.org/amigo/term/GO:0004016

we include "regulates closure" for molecular function by default.

This is a bit misleading if you expect (intuitively) all of the annotations to be 
MF adenylate kinase.

Includes  processes like
	positive regulation of adenylate cyclase activity involved in G-protein coupled receptor signaling pathway
and
activation of adenylate cyclase activity

**Comment by kltm** [comment] 2017-01-12 01:07
I believe this is a duplicate of #210 .

**Closed by kltm** 2017-01-12 01:07 UTC
