### ISSUE TITLE
broken icon image "inferred capable of part of"

### ISSUE THREAD

**Issue by alanruttenberg** [geneontology/amigo#430] opened 2017-05-08 00:33 UTC
For example see http://amigo.geneontology.org/amigo/term/GO:0061773 inferred tree view:

![screen shot 2017-05-07 at 8 32 22 pm](https://cloud.githubusercontent.com/assets/241934/25786497/5e9b12e6-3364-11e7-8dfc-8ecfdbdf230a.PNG)

**Comment by kltm** [comment] 2017-05-08 19:32
Believed to be a duplicate of #215 .

**Closed by kltm** 2017-05-08 19:32 UTC
