### ISSUE TITLE
PTHR family column odd behavior

### ISSUE THREAD

**Issue by pgaudet** [geneontology/amigo#504] opened 2018-05-24 09:54 UTC
Hello, 

http://amigo.geneontology.org/amigo/gene_product/SGD:S000001608
is not showing that it belongs to PTHR12790 - although other family members are OK. 

Also, for some proteins we have other identifiers, even PubMeds - can this be fixed? 
http://amigo.geneontology.org/amigo/term/GO:0001181

![image](https://user-images.githubusercontent.com/4782928/40478382-3536ec38-5f49-11e8-8a44-0f5edd780300.png)

Thanks, Pascale

**Comment by pgaudet** [comment] 2018-05-24 10:15
Also, it's not possible to filter by family even when there are multiple families: 
![image](https://user-images.githubusercontent.com/4782928/40479526-171ce830-5f4c-11e8-9a1a-64c345aa3bb7.png)

**Comment by kltm** [comment] 2018-05-24 18:47
The second part is a dupe of #498

**Comment by kltm** [comment] 2018-05-24 18:57
@pgaudet For the first two issues issues, they are unlikely to have their origins in AmiGO, but rather further up the pipeline. We might want to bring in @dougli1sqrd to help trace back where the issue originates and move this to the proper tracker.

**Comment by pgaudet** [comment] 2018-05-25 05:40
>>     Also, for some proteins we have other identifiers, even PubMeds - can this be fixed?
    http://amigo.geneontology.org/amigo/term/GO:0001181

> sorry not following

See  screenshot - Most IBA anntations have "PAINT_REF:nnnnn" in the Reference column. However we sometimes have other stuff, like PubMed or references from other sources: 
<img width="1155" alt="image" src="https://user-images.githubusercontent.com/4782928/40527813-78bf77cc-5fee-11e8-871e-776538b6f043.png">

**Comment by selewis** [comment] 2018-05-25 18:38
Chris,

for this:

> http://amigo.geneontology.org/amigo/gene_product/SGD:S000001608
> is not showing that it belongs to PTHR12790 - although other family
> members are OK.


It's due to the pipeline loading issue. Some of the MODs have old, out of
date PAINT annotations. Ones that were created based on earlier builds of
the PANTHER family trees. And with each new PANTHER build some families
disappear and newer merges/splits of these take on new PANTHER family
numbers.

**Comment by cmungall** [comment] 2018-05-25 22:06
@pgaudet 

> See screenshot - Most IBA anntations have "PAINT_REF:nnnnn" in the Reference column. However we sometimes have other stuff, like PubMed or references from other sources

This is all covered in https://github.com/geneontology/go-site/issues/587. As we discovered in that ticket, when other groups ingest PAINT they remint the reference ID. See my comment from April 11 in that ticket

@selewis

> It's due to the pipeline loading issue. Some of the MODs have old, out of
> date PAINT annotations. Ones that were created based on earlier builds of
> the PANTHER family trees. And with each new PANTHER build some families
> disappear and newer merges/splits of these take on new PANTHER family
> numbers.

The issue of MODs having old out of date annotations is already covered in:
https://github.com/geneontology/go-site/issues/587

I'm closing this as a dupe. If I've missed something reopen or open another ticket, thanks!

**Closed by cmungall** 2018-05-25 22:06 UTC
Labels: bug (B: affects usability)

**Comment by selewis** [comment] 2018-05-26 04:10
@pgaudet

Is PAINT now reapplying IBAs to leaf nodes that have the experimental? (It
didn't use to)

Just wondering how those other refs might be appearing  and this is one way
we should rule out.

-S

**Comment by pgaudet** [comment] 2018-05-28 07:46
@selewis I don't know the exact process. @huaiyumi, can you please describe the process?
