### ISSUE TITLE
experimental evidence used in manual assertion

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#438] opened 2017-08-27 14:59 UTC
when I use this filter:

evidence_subset_closure_label: experimental evidence used in manual assertion

and  ALL MF annotations, I only return 2110 annotations.

I think it is restricting to EXP (i.e not using ECO relationships?)

**Comment by kltm** [comment] 2017-08-27 17:20
Duplicate of #433 .

**Closed by kltm** 2017-08-27 17:20 UTC
Labels: duplicate
