### ISSUE TITLE
provide non-redundant human dataset in AmiGO

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#470] opened 2018-02-22 14:28 UTC
Currently we have 29081 human proteins

It seems  possibly Intact are submitting Trembl entries?

Is there an easy way to check where the duplicates are coming from and stop it happening?

@bmeldal

**Comment by bmeldal** [comment] 2018-02-22 14:31
Thanks, Val. I've emailed the team.

**Comment by bmeldal** [comment] 2018-02-22 14:43
Sandra confirms, we export TrEMBL entries. It's up to GO to decide if they still want them, provide a ref proteome DS or let users do the filtering according to their needs (e.g. minus PE=5).

**Comment by ValWood** [comment] 2018-02-22 14:49
I don't think it is possible to leave this to users. They will not be able to distinguish between a UniProt or Trembl entry, and for the most part they won't know that they need to ...otherwise the question would have arisen before (or not because we don't have a helpdesk).

Although previously we worked on the principle that Trembl entries only contain inferred, and hence redundant information?  Isn't this the case? Or do Intact annotate both the UniPROT entry and the Trembl entry with the same information ? (which would still be redundant but I thought that manual curation only happened  to  the reference proteome entry) ?

**Comment by bmeldal** [comment] 2018-02-22 14:58
We use TrEMBL entries if the seq used in the expt doesn't match anything in SwissProt. We are picky about using the best match as interactions can be disrupted by small changes. (That doesn't apply to mutations, we annotate them as features of the canonical protein)

**Comment by cmungall** [comment] 2018-02-22 15:31
Goa releases the gcrp for human. The number is due to hgnc ids leaking in
from the paint pipeline. Can someone mark this ticket as a dupe of the
issue Antonia reported on helpdesk? I'm on my phone

**Comment by ValWood** [comment] 2018-02-22 15:34
duplicate of https://github.com/geneontology/helpdesk/issues/99

**Closed** 2018-02-22 19:17 UTC
Labels: duplicate
