### ISSUE TITLE
Download of search on annotation to GO term "protein kinase activity" includes "protein kinase inhibitors and activators"

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#319] opened 2016-03-10 18:32 UTC
follow on from
https://github.com/geneontology/amigo/issues/318

I thought I might be able to use the results anyway. However, now I look at them the download results for 
 search on annotations to GO term "protein kinase activity" includes
 "protein kinase inhibitors" and "activators"

I think this is also in an old ticket but I thought it was already fixed?

**Comment by kltm** [comment] 2016-03-10 21:35
@ValWood If you're doing a textual search for
```
protein kinase activity
```
Things that are "nearby" will also get picked up. This gives something like 87489 results.
A more specific search for (note the quotes):
```
"protein kinase activity"
```
will give 74660 results, which I believe is arrived at by looking at the annotation class closure as well. 
The best, and only recommended, way to get annotations targeted at specific subsections of the graph is to use the side filters to tie yourself to a term in the ontology, either direct or indirect:
http://amigo.geneontology.org/amigo/search/annotation?q=*:*&fq=annotation_class_label:%22protein%20kinase%20activity%22&sfq=document_category:%22annotation%22

**Comment by ValWood** [comment] 2016-03-10 21:51
It was a term search. I searched on "protein kinase activity"
and selected the exact term from the drop down
so I ended up on this page
http://amigo.geneontology.org/amigo/term/GO:0004672

I think the issue is because  annotations are transitive over "regulates" relationship  fo MF again.

**Comment by kltm** [comment] 2016-03-10 22:00
Yes, that page is showing the inferred annotations, so from the AmiGO end it is behaving correctly. I'll tag on @hdietze to check on the correct behavior.

**Comment by ValWood** [comment] 2016-03-10 22:31
That's not what you would expect for molecular function. Protein kinase regulators aren't protein kinases....This has also come up a few times previously. I thought it got fixed though.....

**Comment by kltm** [comment] 2016-03-10 22:33
Taggin @cmungall as well.

**Comment by kltm** [comment] 2016-03-21 22:29
Any thoughts on this gentlemen (@hdietze @cmungall)?

**Comment by cmungall** [comment] 2016-03-21 22:55
I believe this is a dupe of #210

**Closed by cmungall** 2016-03-21 22:55 UTC
Labels: question
